<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body class="min-vh-100 d-flex flex-column">
    <?= $this->fetch('_form_header.phtml') ?>

    <main class="flex-grow-1">
      <div class="container-lg mt-3">
        <h1></h1>
        <div class="row">
          <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
            <h1 class="display-3">Анализатор страниц</h1>
            <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
            <form action="/urls" method="post" class="row" required="">
              <div class="col-8">
                <label for="text" class="visually-hidden">Url для проверки</label>
                <input type="text" name="url[name]" value="" class="
                  <?php if (isset($message)) : ?>
                    is-invalid
                  <?php endif ?>
                  form-control form-control-lg" placeholder="https://www.example.com">
                <?php if (isset($message)): ?>
                  <div class="invalid-feedback"><?= $message ?></div>
                <?php endif ?>
              </div>
              <div class="col-2">
                <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
              </div>
            </form>
          </div>
        </div>
      </div>
    </main>

    <?= $this->fetch('_form_footer.phtml') ?>
  </body>
</html>