<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body class="min-vh-100 d-flex flex-column">
    <?= $this->fetch('_form_header.phtml') ?>

    <?php if (count($flash) > 0): ?>
      <?php foreach ($flash as $messages): ?>
        <?php foreach ($messages as $message): ?>
          <div class="alert alert-<?= $status ?>" role="alert"><?= $message ?></div>
        <?php endforeach ?>
      <?php endforeach ?>
    <?php endif ?>

    <main class="flex-grow-1">
      <div class="container-lg mt-3">
        <h1>Сайт: <?= htmlspecialchars($url) ?></h1>
        <div class="table-responsive">
          <table class="table table-bordered table-hover text-nowrap" data-test="url">
            <tbody>
              <tr>
                <td>ID</td>
                <td><?= htmlspecialchars($id) ?></td>
              </tr>
              <tr>
                <td>Имя</td>
                <td><?= htmlspecialchars($url) ?></td>
              </tr>
              <tr>
                <td>Дата создания</td>
                <td><?= htmlspecialchars($createdAt) ?></td>
              </tr>
            </tbody>
          </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="/urls/<?= htmlspecialchars($id) ?>/checks">
          <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <br>
        <table class="table table-bordered table-hover" data-test="checks">
          <thead>
            <tr>
              <th>ID</th>
              <th>Код ответа</th>
              <th>h1</th>
              <th>title</th>
              <th>description</th>
              <th>Дата создания</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($checks as $check): ?>
              <tr>
                <td><?= htmlspecialchars($check['id']) ?></td>
                <td><?= htmlspecialchars($check['status_code']) ?></td>
                <td><?= htmlspecialchars($check['h1']) ?></td>
                <td><?= htmlspecialchars($check['title']) ?></td>
                <td><?= htmlspecialchars($check['description']) ?></td>
                <td><?= htmlspecialchars($check['created_at']) ?></td>
              </tr>
            <?php endforeach ?>
          </tbody>
        </table>
      </div>
    </main>

    <?= $this->fetch('_form_footer.phtml') ?>
  </body>
</html>