<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body class="min-vh-100 d-flex flex-column">
    <?= $this->fetch('_form_header.phtml') ?>

    <main class="flex-grow-1">
      <div class="container-lg mt-3">
        <h1>Сайты</h1>
        <div class="table-responsive">
          <table class="table table-bordered table-hover text-nowrap" data-test="urls">
            <thead>
              <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Последняя проверка</th>
                <th>Код ответа</th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($urls as $url): ?>
                <tr>
                  <td><?= htmlspecialchars($url['id']) ?></td>
                  <td><a href="/urls/<?= htmlspecialchars($url['id']) ?>"><?= htmlspecialchars($url['name']) ?></a></td>
                  <td><?= htmlspecialchars($url['last_check'])?></td>
                  <td><?= htmlspecialchars($url['status_code'])?></td>
                </tr>
              <?php endforeach ?>
            </tbody>
          </table>
        </div>
      </div>
    </main>
    
    <?= $this->fetch('_form_footer.phtml') ?>
  </body>
</html>