<!DOCTYPE html>
<html lang="ru">
  <?php require '_form_head.phtml' ?>

  <body class="min-vh-100 d-flex flex-column">
    <?php require '_form_header.phtml' ?>

    <main class="flex-grow-1">
      <div class="container-lg mt-3">
        <h1>Сайты</h1>
        <div class="table-responsive">
          <table class="table table-bordered table-hover text-nowrap" data-test="urls">
            <thead>
              <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Последняя проверка</th>
                <th>Код ответа</th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($urls as $url): ?>
                <tr>
                  <td><?= htmlspecialchars($url['id']) ?></td>
                  <td><a href="/urls/<?= htmlspecialchars($url['id']) ?>"><?= htmlspecialchars($url['name']) ?></a></td>
                  <td><?= htmlspecialchars($url['last_check'])?></td>
                  <td><?= htmlspecialchars($url['status_code'])?></td>
                </tr>
              <?php endforeach ?>
            </tbody>
          </table>
        </div>
      </div>
    </main>
    
    <?php require '_form_footer.phtml' ?>
  </body>
</html>